// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	strictgin "github.com/oapi-codegen/runtime/strictmiddleware/gin"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// LoginInput defines model for LoginInput.
type LoginInput struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// Post defines model for Post.
type Post struct {
	// Content Markdown content
	Content   *string    `json:"content,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
	Id        *int       `json:"id,omitempty"`
	Slug      *string    `json:"slug,omitempty"`
	Title     *string    `json:"title,omitempty"`
}

// PostInput defines model for PostInput.
type PostInput struct {
	Content string `json:"content"`
	Title   string `json:"title"`
}

// TokenResponse defines model for TokenResponse.
type TokenResponse struct {
	Token *string `json:"token,omitempty"`
}

// PostAuthLoginJSONRequestBody defines body for PostAuthLogin for application/json ContentType.
type PostAuthLoginJSONRequestBody = LoginInput

// PostPostsJSONRequestBody defines body for PostPosts for application/json ContentType.
type PostPostsJSONRequestBody = PostInput

// PutPostsSlugJSONRequestBody defines body for PutPostsSlug for application/json ContentType.
type PutPostsSlugJSONRequestBody = PostInput

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Admin Login
	// (POST /auth/login)
	PostAuthLogin(c *gin.Context)
	// Alle Posts abrufen
	// (GET /posts)
	GetPosts(c *gin.Context)
	// Post erstellen (Admin)
	// (POST /posts)
	PostPosts(c *gin.Context)
	// Post löschen (Admin)
	// (DELETE /posts/{slug})
	DeletePostsSlug(c *gin.Context, slug string)
	// Einzelnen Post abrufen
	// (GET /posts/{slug})
	GetPostsSlug(c *gin.Context, slug string)
	// Post aktualisieren (Admin)
	// (PUT /posts/{slug})
	PutPostsSlug(c *gin.Context, slug string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// PostAuthLogin operation middleware
func (siw *ServerInterfaceWrapper) PostAuthLogin(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostAuthLogin(c)
}

// GetPosts operation middleware
func (siw *ServerInterfaceWrapper) GetPosts(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetPosts(c)
}

// PostPosts operation middleware
func (siw *ServerInterfaceWrapper) PostPosts(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostPosts(c)
}

// DeletePostsSlug operation middleware
func (siw *ServerInterfaceWrapper) DeletePostsSlug(c *gin.Context) {

	var err error

	// ------------- Path parameter "slug" -------------
	var slug string

	err = runtime.BindStyledParameterWithOptions("simple", "slug", c.Param("slug"), &slug, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter slug: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeletePostsSlug(c, slug)
}

// GetPostsSlug operation middleware
func (siw *ServerInterfaceWrapper) GetPostsSlug(c *gin.Context) {

	var err error

	// ------------- Path parameter "slug" -------------
	var slug string

	err = runtime.BindStyledParameterWithOptions("simple", "slug", c.Param("slug"), &slug, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter slug: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetPostsSlug(c, slug)
}

// PutPostsSlug operation middleware
func (siw *ServerInterfaceWrapper) PutPostsSlug(c *gin.Context) {

	var err error

	// ------------- Path parameter "slug" -------------
	var slug string

	err = runtime.BindStyledParameterWithOptions("simple", "slug", c.Param("slug"), &slug, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter slug: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PutPostsSlug(c, slug)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/auth/login", wrapper.PostAuthLogin)
	router.GET(options.BaseURL+"/posts", wrapper.GetPosts)
	router.POST(options.BaseURL+"/posts", wrapper.PostPosts)
	router.DELETE(options.BaseURL+"/posts/:slug", wrapper.DeletePostsSlug)
	router.GET(options.BaseURL+"/posts/:slug", wrapper.GetPostsSlug)
	router.PUT(options.BaseURL+"/posts/:slug", wrapper.PutPostsSlug)
}

type PostAuthLoginRequestObject struct {
	Body *PostAuthLoginJSONRequestBody
}

type PostAuthLoginResponseObject interface {
	VisitPostAuthLoginResponse(w http.ResponseWriter) error
}

type PostAuthLogin200JSONResponse TokenResponse

func (response PostAuthLogin200JSONResponse) VisitPostAuthLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostAuthLogin401Response struct {
}

func (response PostAuthLogin401Response) VisitPostAuthLoginResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type GetPostsRequestObject struct {
}

type GetPostsResponseObject interface {
	VisitGetPostsResponse(w http.ResponseWriter) error
}

type GetPosts200JSONResponse []Post

func (response GetPosts200JSONResponse) VisitGetPostsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetPosts500Response struct {
}

func (response GetPosts500Response) VisitGetPostsResponse(w http.ResponseWriter) error {
	w.WriteHeader(500)
	return nil
}

type PostPostsRequestObject struct {
	Body *PostPostsJSONRequestBody
}

type PostPostsResponseObject interface {
	VisitPostPostsResponse(w http.ResponseWriter) error
}

type PostPosts201JSONResponse Post

func (response PostPosts201JSONResponse) VisitPostPostsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type PostPosts400Response struct {
}

func (response PostPosts400Response) VisitPostPostsResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type PostPosts401Response struct {
}

func (response PostPosts401Response) VisitPostPostsResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type PostPosts409Response struct {
}

func (response PostPosts409Response) VisitPostPostsResponse(w http.ResponseWriter) error {
	w.WriteHeader(409)
	return nil
}

type DeletePostsSlugRequestObject struct {
	Slug string `json:"slug"`
}

type DeletePostsSlugResponseObject interface {
	VisitDeletePostsSlugResponse(w http.ResponseWriter) error
}

type DeletePostsSlug204Response struct {
}

func (response DeletePostsSlug204Response) VisitDeletePostsSlugResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeletePostsSlug401Response struct {
}

func (response DeletePostsSlug401Response) VisitDeletePostsSlugResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type DeletePostsSlug404Response struct {
}

func (response DeletePostsSlug404Response) VisitDeletePostsSlugResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type GetPostsSlugRequestObject struct {
	Slug string `json:"slug"`
}

type GetPostsSlugResponseObject interface {
	VisitGetPostsSlugResponse(w http.ResponseWriter) error
}

type GetPostsSlug200JSONResponse Post

func (response GetPostsSlug200JSONResponse) VisitGetPostsSlugResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetPostsSlug404Response struct {
}

func (response GetPostsSlug404Response) VisitGetPostsSlugResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type PutPostsSlugRequestObject struct {
	Slug string `json:"slug"`
	Body *PutPostsSlugJSONRequestBody
}

type PutPostsSlugResponseObject interface {
	VisitPutPostsSlugResponse(w http.ResponseWriter) error
}

type PutPostsSlug200JSONResponse Post

func (response PutPostsSlug200JSONResponse) VisitPutPostsSlugResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PutPostsSlug400Response struct {
}

func (response PutPostsSlug400Response) VisitPutPostsSlugResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type PutPostsSlug401Response struct {
}

func (response PutPostsSlug401Response) VisitPutPostsSlugResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type PutPostsSlug404Response struct {
}

func (response PutPostsSlug404Response) VisitPutPostsSlugResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type PutPostsSlug409Response struct {
}

func (response PutPostsSlug409Response) VisitPutPostsSlugResponse(w http.ResponseWriter) error {
	w.WriteHeader(409)
	return nil
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Admin Login
	// (POST /auth/login)
	PostAuthLogin(ctx context.Context, request PostAuthLoginRequestObject) (PostAuthLoginResponseObject, error)
	// Alle Posts abrufen
	// (GET /posts)
	GetPosts(ctx context.Context, request GetPostsRequestObject) (GetPostsResponseObject, error)
	// Post erstellen (Admin)
	// (POST /posts)
	PostPosts(ctx context.Context, request PostPostsRequestObject) (PostPostsResponseObject, error)
	// Post löschen (Admin)
	// (DELETE /posts/{slug})
	DeletePostsSlug(ctx context.Context, request DeletePostsSlugRequestObject) (DeletePostsSlugResponseObject, error)
	// Einzelnen Post abrufen
	// (GET /posts/{slug})
	GetPostsSlug(ctx context.Context, request GetPostsSlugRequestObject) (GetPostsSlugResponseObject, error)
	// Post aktualisieren (Admin)
	// (PUT /posts/{slug})
	PutPostsSlug(ctx context.Context, request PutPostsSlugRequestObject) (PutPostsSlugResponseObject, error)
}

type StrictHandlerFunc = strictgin.StrictGinHandlerFunc
type StrictMiddlewareFunc = strictgin.StrictGinMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// PostAuthLogin operation middleware
func (sh *strictHandler) PostAuthLogin(ctx *gin.Context) {
	var request PostAuthLoginRequestObject

	var body PostAuthLoginJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostAuthLogin(ctx, request.(PostAuthLoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostAuthLogin")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(PostAuthLoginResponseObject); ok {
		if err := validResponse.VisitPostAuthLoginResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetPosts operation middleware
func (sh *strictHandler) GetPosts(ctx *gin.Context) {
	var request GetPostsRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetPosts(ctx, request.(GetPostsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetPosts")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetPostsResponseObject); ok {
		if err := validResponse.VisitGetPostsResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostPosts operation middleware
func (sh *strictHandler) PostPosts(ctx *gin.Context) {
	var request PostPostsRequestObject

	var body PostPostsJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostPosts(ctx, request.(PostPostsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostPosts")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(PostPostsResponseObject); ok {
		if err := validResponse.VisitPostPostsResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeletePostsSlug operation middleware
func (sh *strictHandler) DeletePostsSlug(ctx *gin.Context, slug string) {
	var request DeletePostsSlugRequestObject

	request.Slug = slug

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeletePostsSlug(ctx, request.(DeletePostsSlugRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeletePostsSlug")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(DeletePostsSlugResponseObject); ok {
		if err := validResponse.VisitDeletePostsSlugResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetPostsSlug operation middleware
func (sh *strictHandler) GetPostsSlug(ctx *gin.Context, slug string) {
	var request GetPostsSlugRequestObject

	request.Slug = slug

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetPostsSlug(ctx, request.(GetPostsSlugRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetPostsSlug")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetPostsSlugResponseObject); ok {
		if err := validResponse.VisitGetPostsSlugResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// PutPostsSlug operation middleware
func (sh *strictHandler) PutPostsSlug(ctx *gin.Context, slug string) {
	var request PutPostsSlugRequestObject

	request.Slug = slug

	var body PutPostsSlugJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PutPostsSlug(ctx, request.(PutPostsSlugRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PutPostsSlug")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(PutPostsSlugResponseObject); ok {
		if err := validResponse.VisitPutPostsSlugResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8RVQU/cOhD+K5HfO7wnpZul0ENzgxYqEJVQAXFAq8qbzCYGx07HY9CC8rd66o0/Vtlm",
	"SZbNbqGF7c2xx+OZ7/vmyy3LdFVrBYoMS2+ZyUqouF8e6kKofVVbcl816hqQBPizmhtzrTF3a5rWwFJm",
	"CIUqWBMzawAVr6DnsIkZwjcrEHKWnreRcZtxFM8u6fEFZOQyHmnTU0SmFYHyBzmYDEVNQiuWss8cL3N9",
	"raJZRLxYZIbACfKv3N+faKzciuWc4A0JX9LCHdHtVyiCAtDtG2mLXiRIkFwCQ2+PS9DuNPqcJ7pIh7D4",
	"IVUfyif6EtQXMLVWBharIHf8pGYcJJBZFDQ9dnoK98fAEXDbUtl+7c1wPzg7YXFQn8sUTlsOSqKaNS6x",
	"UBPtiwh9sx2pi2j7aJ/F7ArQBAFsDIaDoWtJ16B4LVjKNgfDwabXGZW+nIRbKhPpRO57vZeY65g7He3n",
	"LPWkuIr9LLAAKRja0fn0ETG8rqXI/M3kwmjVDpNb/YswYSn7J2mnLbkftaQzZ808bYQW/EagxJf9djh8",
	"sZfnCfePzw/SwdlJ5IMcllvDjcVR2+PSZYs+IOSgSHBpAv+2qjhOWcq280qoaAYg8cI4PXoZjFxk4pD3",
	"rRXQw8AnoCMf8Ic4CILK/AoQ7zOtnjkin/bhcigMQcSlBIxCdU3M3oWK5iOPAa8Aoz0opfOKeWSkhHA9",
	"4mO0E+gCFNKOmniFMltgXl6VrR09SZQbL/pwH+ZuPwI0BFJS0GMP3qequPshSRQQ7QpV8DEsle6pcg6g",
	"UdxAHoLe9/AnbRGNAUGQia40llzlbhw6FsfS83lzOx81oy7P3cpBRf/5ifi/h+uHaUhu3S+lCeVIIFjk",
	"/6Pf9zddjd7ZkFdAgMZX5GzNux2LWfgbh//UYy7jDi+PnX20wPPWIkS+vQLk3XeTlfQMuJflUiIrXcaJ",
	"/U2sQykroY5Xu806IR2uZ3RaPJ+L/QO4u0LdgFSgvGutNi3b51l2Lej+dTNcE6P8kiyXwgjAVzLEp6rk",
	"tc2z0+lqA22anwEAAP//3GZ2atEMAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
